// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2.proto

package com.ww.hbase.coprocessor.avg;

public final class AVG {
  private AVG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AvgRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string family = 1;
    /**
     * <code>required string family = 1;</code>
     */
    boolean hasFamily();
    /**
     * <code>required string family = 1;</code>
     */
    String getFamily();
    /**
     * <code>required string family = 1;</code>
     */
    com.google.protobuf.ByteString
        getFamilyBytes();

    // required string column = 2;
    /**
     * <code>required string column = 2;</code>
     */
    boolean hasColumn();
    /**
     * <code>required string column = 2;</code>
     */
    String getColumn();
    /**
     * <code>required string column = 2;</code>
     */
    com.google.protobuf.ByteString
        getColumnBytes();
  }
  /**
   * Protobuf type {@code AvgRequest}
   */
  public static final class AvgRequest extends
      com.google.protobuf.GeneratedMessage
      implements AvgRequestOrBuilder {
    // Use AvgRequest.newBuilder() to construct.
    private AvgRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AvgRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AvgRequest defaultInstance;
    public static AvgRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AvgRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AvgRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              family_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              column_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ww.hbase.coprocessor.avg.AVG.AvgRequest.class, com.ww.hbase.coprocessor.avg.AVG.AvgRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AvgRequest> PARSER =
        new com.google.protobuf.AbstractParser<AvgRequest>() {
      public AvgRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AvgRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<AvgRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string family = 1;
    public static final int FAMILY_FIELD_NUMBER = 1;
    private Object family_;
    /**
     * <code>required string family = 1;</code>
     */
    public boolean hasFamily() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string family = 1;</code>
     */
    public String getFamily() {
      Object ref = family_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          family_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string family = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      Object ref = family_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string column = 2;
    public static final int COLUMN_FIELD_NUMBER = 2;
    private Object column_;
    /**
     * <code>required string column = 2;</code>
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string column = 2;</code>
     */
    public String getColumn() {
      Object ref = column_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          column_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string column = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      Object ref = column_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      family_ = "";
      column_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFamily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getColumnBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getColumnBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ww.hbase.coprocessor.avg.AVG.AvgRequest)) {
        return super.equals(obj);
      }
      com.ww.hbase.coprocessor.avg.AVG.AvgRequest other = (com.ww.hbase.coprocessor.avg.AVG.AvgRequest) obj;

      boolean result = true;
      result = result && (hasFamily() == other.hasFamily());
      if (hasFamily()) {
        result = result && getFamily()
            .equals(other.getFamily());
      }
      result = result && (hasColumn() == other.hasColumn());
      if (hasColumn()) {
        result = result && getColumn()
            .equals(other.getColumn());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFamily()) {
        hash = (37 * hash) + FAMILY_FIELD_NUMBER;
        hash = (53 * hash) + getFamily().hashCode();
      }
      if (hasColumn()) {
        hash = (37 * hash) + COLUMN_FIELD_NUMBER;
        hash = (53 * hash) + getColumn().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ww.hbase.coprocessor.avg.AVG.AvgRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AvgRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ww.hbase.coprocessor.avg.AVG.AvgRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ww.hbase.coprocessor.avg.AVG.AvgRequest.class, com.ww.hbase.coprocessor.avg.AVG.AvgRequest.Builder.class);
      }

      // Construct using com.ww.hbase.coprocessor.avg.AVG.AvgRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        family_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgRequest_descriptor;
      }

      public com.ww.hbase.coprocessor.avg.AVG.AvgRequest getDefaultInstanceForType() {
        return com.ww.hbase.coprocessor.avg.AVG.AvgRequest.getDefaultInstance();
      }

      public com.ww.hbase.coprocessor.avg.AVG.AvgRequest build() {
        com.ww.hbase.coprocessor.avg.AVG.AvgRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ww.hbase.coprocessor.avg.AVG.AvgRequest buildPartial() {
        com.ww.hbase.coprocessor.avg.AVG.AvgRequest result = new com.ww.hbase.coprocessor.avg.AVG.AvgRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.family_ = family_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.column_ = column_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ww.hbase.coprocessor.avg.AVG.AvgRequest) {
          return mergeFrom((com.ww.hbase.coprocessor.avg.AVG.AvgRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ww.hbase.coprocessor.avg.AVG.AvgRequest other) {
        if (other == com.ww.hbase.coprocessor.avg.AVG.AvgRequest.getDefaultInstance()) return this;
        if (other.hasFamily()) {
          bitField0_ |= 0x00000001;
          family_ = other.family_;
          onChanged();
        }
        if (other.hasColumn()) {
          bitField0_ |= 0x00000002;
          column_ = other.column_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFamily()) {
          
          return false;
        }
        if (!hasColumn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ww.hbase.coprocessor.avg.AVG.AvgRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ww.hbase.coprocessor.avg.AVG.AvgRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string family = 1;
      private Object family_ = "";
      /**
       * <code>required string family = 1;</code>
       */
      public boolean hasFamily() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string family = 1;</code>
       */
      public String getFamily() {
        Object ref = family_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          family_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string family = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFamilyBytes() {
        Object ref = family_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          family_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder setFamily(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder clearFamily() {
        bitField0_ = (bitField0_ & ~0x00000001);
        family_ = getDefaultInstance().getFamily();
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder setFamilyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        family_ = value;
        onChanged();
        return this;
      }

      // required string column = 2;
      private Object column_ = "";
      /**
       * <code>required string column = 2;</code>
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string column = 2;</code>
       */
      public String getColumn() {
        Object ref = column_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          column_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string column = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder setColumn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AvgRequest)
    }

    static {
      defaultInstance = new AvgRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AvgRequest)
  }

  public interface AvgResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 sum = 1 [default = 0];
    /**
     * <code>required int64 sum = 1 [default = 0];</code>
     */
    boolean hasSum();
    /**
     * <code>required int64 sum = 1 [default = 0];</code>
     */
    long getSum();

    // required int64 count = 22 [default = 0];
    /**
     * <code>required int64 count = 22 [default = 0];</code>
     */
    boolean hasCount();
    /**
     * <code>required int64 count = 22 [default = 0];</code>
     */
    long getCount();
  }
  /**
   * Protobuf type {@code AvgResponse}
   */
  public static final class AvgResponse extends
      com.google.protobuf.GeneratedMessage
      implements AvgResponseOrBuilder {
    // Use AvgResponse.newBuilder() to construct.
    private AvgResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AvgResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AvgResponse defaultInstance;
    public static AvgResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AvgResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AvgResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sum_ = input.readInt64();
              break;
            }
            case 176: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ww.hbase.coprocessor.avg.AVG.AvgResponse.class, com.ww.hbase.coprocessor.avg.AVG.AvgResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AvgResponse> PARSER =
        new com.google.protobuf.AbstractParser<AvgResponse>() {
      public AvgResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AvgResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<AvgResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 sum = 1 [default = 0];
    public static final int SUM_FIELD_NUMBER = 1;
    private long sum_;
    /**
     * <code>required int64 sum = 1 [default = 0];</code>
     */
    public boolean hasSum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sum = 1 [default = 0];</code>
     */
    public long getSum() {
      return sum_;
    }

    // required int64 count = 22 [default = 0];
    public static final int COUNT_FIELD_NUMBER = 22;
    private long count_;
    /**
     * <code>required int64 count = 22 [default = 0];</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 count = 22 [default = 0];</code>
     */
    public long getCount() {
      return count_;
    }

    private void initFields() {
      sum_ = 0L;
      count_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(22, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(22, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ww.hbase.coprocessor.avg.AVG.AvgResponse)) {
        return super.equals(obj);
      }
      com.ww.hbase.coprocessor.avg.AVG.AvgResponse other = (com.ww.hbase.coprocessor.avg.AVG.AvgResponse) obj;

      boolean result = true;
      result = result && (hasSum() == other.hasSum());
      if (hasSum()) {
        result = result && (getSum()
            == other.getSum());
      }
      result = result && (hasCount() == other.hasCount());
      if (hasCount()) {
        result = result && (getCount()
            == other.getCount());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSum()) {
        hash = (37 * hash) + SUM_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getSum());
      }
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getCount());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ww.hbase.coprocessor.avg.AVG.AvgResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ww.hbase.coprocessor.avg.AVG.AvgResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AvgResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ww.hbase.coprocessor.avg.AVG.AvgResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ww.hbase.coprocessor.avg.AVG.AvgResponse.class, com.ww.hbase.coprocessor.avg.AVG.AvgResponse.Builder.class);
      }

      // Construct using com.ww.hbase.coprocessor.avg.AVG.AvgResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ww.hbase.coprocessor.avg.AVG.internal_static_AvgResponse_descriptor;
      }

      public com.ww.hbase.coprocessor.avg.AVG.AvgResponse getDefaultInstanceForType() {
        return com.ww.hbase.coprocessor.avg.AVG.AvgResponse.getDefaultInstance();
      }

      public com.ww.hbase.coprocessor.avg.AVG.AvgResponse build() {
        com.ww.hbase.coprocessor.avg.AVG.AvgResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ww.hbase.coprocessor.avg.AVG.AvgResponse buildPartial() {
        com.ww.hbase.coprocessor.avg.AVG.AvgResponse result = new com.ww.hbase.coprocessor.avg.AVG.AvgResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sum_ = sum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ww.hbase.coprocessor.avg.AVG.AvgResponse) {
          return mergeFrom((com.ww.hbase.coprocessor.avg.AVG.AvgResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ww.hbase.coprocessor.avg.AVG.AvgResponse other) {
        if (other == com.ww.hbase.coprocessor.avg.AVG.AvgResponse.getDefaultInstance()) return this;
        if (other.hasSum()) {
          setSum(other.getSum());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSum()) {
          
          return false;
        }
        if (!hasCount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ww.hbase.coprocessor.avg.AVG.AvgResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ww.hbase.coprocessor.avg.AVG.AvgResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 sum = 1 [default = 0];
      private long sum_ ;
      /**
       * <code>required int64 sum = 1 [default = 0];</code>
       */
      public boolean hasSum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sum = 1 [default = 0];</code>
       */
      public long getSum() {
        return sum_;
      }
      /**
       * <code>required int64 sum = 1 [default = 0];</code>
       */
      public Builder setSum(long value) {
        bitField0_ |= 0x00000001;
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sum = 1 [default = 0];</code>
       */
      public Builder clearSum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sum_ = 0L;
        onChanged();
        return this;
      }

      // required int64 count = 22 [default = 0];
      private long count_ ;
      /**
       * <code>required int64 count = 22 [default = 0];</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 count = 22 [default = 0];</code>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>required int64 count = 22 [default = 0];</code>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 count = 22 [default = 0];</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AvgResponse)
    }

    static {
      defaultInstance = new AvgResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AvgResponse)
  }

  /**
   * Protobuf service {@code AvgService}
   */
  public static abstract class AvgService
      implements com.google.protobuf.Service {
    protected AvgService() {}

    public interface Interface {
      /**
       * <code>rpc getAvg(.AvgRequest) returns (.AvgResponse);</code>
       */
      public abstract void getAvg(
              com.google.protobuf.RpcController controller,
              com.ww.hbase.coprocessor.avg.AVG.AvgRequest request,
              com.google.protobuf.RpcCallback<com.ww.hbase.coprocessor.avg.AVG.AvgResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new AvgService() {
        @Override
        public  void getAvg(
            com.google.protobuf.RpcController controller,
            com.ww.hbase.coprocessor.avg.AVG.AvgRequest request,
            com.google.protobuf.RpcCallback<com.ww.hbase.coprocessor.avg.AVG.AvgResponse> done) {
          impl.getAvg(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getAvg(controller, (com.ww.hbase.coprocessor.avg.AVG.AvgRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.ww.hbase.coprocessor.avg.AVG.AvgRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.ww.hbase.coprocessor.avg.AVG.AvgResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getAvg(.AvgRequest) returns (.AvgResponse);</code>
     */
    public abstract void getAvg(
        com.google.protobuf.RpcController controller,
        com.ww.hbase.coprocessor.avg.AVG.AvgRequest request,
        com.google.protobuf.RpcCallback<com.ww.hbase.coprocessor.avg.AVG.AvgResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.ww.hbase.coprocessor.avg.AVG.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getAvg(controller, (com.ww.hbase.coprocessor.avg.AVG.AvgRequest)request,
            com.google.protobuf.RpcUtil.<com.ww.hbase.coprocessor.avg.AVG.AvgResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.ww.hbase.coprocessor.avg.AVG.AvgRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.ww.hbase.coprocessor.avg.AVG.AvgResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.ww.hbase.coprocessor.avg.AVG.AvgService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getAvg(
          com.google.protobuf.RpcController controller,
          com.ww.hbase.coprocessor.avg.AVG.AvgRequest request,
          com.google.protobuf.RpcCallback<com.ww.hbase.coprocessor.avg.AVG.AvgResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.ww.hbase.coprocessor.avg.AVG.AvgResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.ww.hbase.coprocessor.avg.AVG.AvgResponse.class,
            com.ww.hbase.coprocessor.avg.AVG.AvgResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.ww.hbase.coprocessor.avg.AVG.AvgResponse getAvg(
              com.google.protobuf.RpcController controller,
              com.ww.hbase.coprocessor.avg.AVG.AvgRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.ww.hbase.coprocessor.avg.AVG.AvgResponse getAvg(
          com.google.protobuf.RpcController controller,
          com.ww.hbase.coprocessor.avg.AVG.AvgRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.ww.hbase.coprocessor.avg.AVG.AvgResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.ww.hbase.coprocessor.avg.AVG.AvgResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:AvgService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AvgRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AvgRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AvgResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AvgResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\0072.proto\",\n\nAvgRequest\022\016\n\006family\030\001 \002(\t\022" +
      "\016\n\006column\030\002 \002(\t\"/\n\013AvgResponse\022\016\n\003sum\030\001 " +
      "\002(\003:\0010\022\020\n\005count\030\026 \002(\003:\001021\n\nAvgService\022#" +
      "\n\006getAvg\022\013.AvgRequest\032\014.AvgResponseB9\n*o" +
      "rg.myname.hbase.coprocessor.autogenerate" +
      "dB\003AVGH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AvgRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AvgRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AvgRequest_descriptor,
              new String[] { "Family", "Column", });
          internal_static_AvgResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_AvgResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AvgResponse_descriptor,
              new String[] { "Sum", "Count", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
